// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var InternalCoreinternalGoldendatasetDontEmitV0NetworkConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"internal.coreinternal.goldendataset.DontEmitV0NetworkConventions",
	featuregate.StageBeta,
	featuregate.WithRegisterDescription("When enabled, goldendataset no longer generates spans with deprecated semconv v1.12.0/1.20.0 attributes (net.host.ip, net.peer.ip, http.host, http.server_name, http.client_ip)."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45076"),
	featuregate.WithRegisterFromVersion("v0.147.0"),
)

var InternalCoreinternalGoldendatasetDontEmitV0RPCConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"internal.coreinternal.goldendataset.DontEmitV0RPCConventions",
	featuregate.StageBeta,
	featuregate.WithRegisterDescription("When enabled, goldendataset no longer generates spans with deprecated semconv RPC attributes rpc.service and peer.service."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/47548"),
	featuregate.WithRegisterFromVersion("v0.148.0"),
)

var InternalCoreinternalGoldendatasetEmitV1NetworkConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"internal.coreinternal.goldendataset.EmitV1NetworkConventions",
	featuregate.StageBeta,
	featuregate.WithRegisterDescription("When enabled, goldendataset generates spans with network.local.address, network.peer.address, server.address, and client.address (semconv v1.38.0+) instead of the deprecated net.host.ip, net.peer.ip, http.host, http.server_name, http.client_ip (semconv v1.12.0/1.20.0). Enable together with pkg.translator.zipkin.EmitV1NetworkConventions for consistent round-trip translation in tests."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45076"),
	featuregate.WithRegisterFromVersion("v0.147.0"),
)

var InternalCoreinternalGoldendatasetEmitV1RPCConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"internal.coreinternal.goldendataset.EmitV1RPCConventions",
	featuregate.StageBeta,
	featuregate.WithRegisterDescription("When enabled, goldendataset generates spans with rpc.method and service.peer.name (semconv v1.40.0) alongside legacy rpc.service and peer.service to support migration."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/47548"),
	featuregate.WithRegisterFromVersion("v0.148.0"),
)
